#pragma once

#define MAX_POST_CONTENT_LEN 121
#define MAX_USERNAME_LEN 13
#define MIN_USERNAME_LEN 4
#define MAX_PASSWORD_LEN 31
#define MIN_PASSWORD_LEN 5
#define MAX_BIO_LEN MAX_POST_CONTENT_LEN
#define MAX_EMAIL_LEN MAX_PASSWORD_LEN


